name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag matheusaquatico/my-image-name:latest
    - name: publish
      run: 
        docker login -u matheusaquatico -p ${{ secrets.Docker_HUB_TOKEN }}
        docker push matheusaquatico/my-image-name:latest
