name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag matheusaquatico/easy-pokedex:latest
    - name: publish
      run: |
        docker login -u matheusaquatico -p ${{ secrets.Docker_HUB_TOKEN }}
        docker push matheusaquatico/easy-pokedex:latest
    - name: register
      run: |
        docker login -u MatheusMarinhoLeca -p ${{ secrets.GH_PAT }} ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/matheusmarinholeca/easy-pokedex:latest
        docker push ghcr.io/matheusmarinholeca/easy-pokedex:latest
